models/Project.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "project".
 *
 * @property integer $id
 * @property string $name
 * @property string $kurs
 * @property string $datetime
 * @property integer $status
 */
class Project extends \yii\db\ActiveRecord
{

    public $investors;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'status'], 'required'],
            [['status', 'avatar_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['kurs', 'datetime'], 'string', 'max' => 45],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'kurs' => 'Курс',
            'datetime' => 'Дата',
            'status' => 'Статус',
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->datetime = time();
            }
            return true;
        }
        return false;
    }

    public function getAvatar()
    {
        return $this->hasOne(Photo::className(), ['id' => 'avatar_id']);
    }

    public function getStatuses()
    {
        return $this->hasOne(Status::className(), ['id' => 'status']);
    }

    public function getSum($id)
    {
        $money = $this->getInvestion($id);
        $minus = $this->getMinus($id);
        print_r($minus);die();
        if (Yii::$app->user->can('admin')) {
            $sum = $money - $minus;
        } else {

            $investor = Investor::find()->where(['project_id' => $id, 'investor_id' => Yii::$app->user->id])->one();
            $persent = $investor->persent / 100;
            $minus = $minus * $persent;
            $sum = $money - $minus;
        }

        if ($sum < 0) {

            $return = '<span class="label bg-red "> ' . '-' . $sum . '</span>';
        }
        if ($sum == 0) {

            $return = '<span class="label bg-green "> ' . $sum . '</span>';
        }
        if ($sum > 0) {

            $return = '<span class="label bg-blue "> ' . '+' . $sum . '</span>';
        }


        return $return;
    }


    public function getSumAll($id)
    {

        $investor_money = InvestorProject::find()->where(['project_id' => $id])->all();
        $money = 0;
        foreach ($investor_money as $investor) {
            $money += $investor->money;
        }
        $material = $this->getMoneyMaterialMinus($id);
        $work = $this->getMoneyWorkMinus($id);
        $sum = $money - $material - $work;
        return $sum;
    }


    public function getSumAllusd($id)
    {

        $investor_money = InvestorProject::find()->where(['project_id' => $id])->all();
        $money = 0;
        foreach ($investor_money as $investor) {
            $money += $investor->money_usd;
        }
        $material = $this->getMoneyMaterialMinus($id);
        $work = $this->getMoneyWorkMinus($id);
        $sum = $money - $material - $work;
        return $sum;
    }


    public function getMoneyMaterialMinus($id)
    {
//        print_r($id);
        $materialMoney = MaterialMoney::find()->where(['project_id' => $id,'type'=>'2'])->all();
//        print_r($materialMoney);
        $minus = 0;
        foreach ($materialMoney as $money) {
            $minus += $money->money;
        }
        return $minus;
    }


    public function getMoneyWorkMinus($id)
    {
        $workMoney = WorkMoney::find()->where(['project_id' => $id,'type'=>'1'])->all();

        $minus = 0;
        foreach ($workMoney as $money) {
            $minus += $money->money;
        }
        return $minus;
    }

    public function getMoneyMaterialNoPaid($id)
    {
        $minus = $this->getMoneyMaterialMinus($id);
        $material = Fabric::find()->where(['project_id' => $id])->all();
//        print_r($material);die();
        $paid = 0;
        foreach ($material as $money) {
            $paid += $money->money;
        }
//        if(Yii::$app->user->can('admin')){
            $return = $paid - $minus;
//        }else {
//            $kurs = UsdKurs::find()->where(['datetime'=>date('Y-m-d')])->one();
//            $return = round(($paid - $minus)/$kurs->kurs,2);
//        }
        return $return;
    }

    public function getMoneyWorkNoPaid($id)
    {
        $minus = $this->getMoneyWorkMinus($id);
        $work = Work::find()->where(['project_id' => $id])->all();
        $paid = 0;
        foreach ($work as $money) {
            $paid += $money->money;
        }
//        if(Yii::$app->user->can('admin')){
            $return = $paid - $minus;
//        }else {
//            $kurs = UsdKurs::find()->where(['datetime'=>date('Y-m-d')])->one();
//            $return = round(($paid - $minus)/$kurs->kurs,2);
//        }
        return $return;
    }


    public function getInvestion($id)
    {
        if (Yii::$app->user->can('admin')) {
            $investor_money = InvestorProject::find()->where(['project_id' => $id])->all();
        } else {
            $investor_money = InvestorProject::find()->where(['project_id' => $id, 'investor_id' => Yii::$app->user->id])->all();
        }
        $money = 0;
        foreach ($investor_money as $investor) {
            $money += $investor->money;
        }
        return $money;
    }

    public function getInvestionusd($id)
    {
        if (Yii::$app->user->can('admin')) {
            $investor_money = InvestorProject::find()->where(['project_id' => $id])->all();
        } else {
            $investor_money = InvestorProject::find()->where(['project_id' => $id, 'investor_id' => Yii::$app->user->id])->all();
        }
        $money = 0;
        foreach ($investor_money as $investor) {
            $money += $investor->money_usd;
        }
        return $money;
    }


    public function getMinus($id)
    {
        if (Yii::$app->user->can('admin')) {
            $works = Work::find()->where(['project_id' => $id, 'status_id' => 2])->all();
        } else {
            $works = Work::find()->where(['project_id' => $id, 'status_id' => 2])->all();
        }
        $sum = 0;
        if (!empty($works)) {
            foreach ($works as $work) {
                $sum += $work->money;
            }
        }
        return $sum;
    }

//    public function getInvestor()
//    {
//        return $this->hasMany(Investor::className(), ['project_id' => 'id']);
//    }


    public function getInvestor()
    {
        return $this->hasMany(InvestorProject::className(), ['project_id'=>'id']);
    }

    public function getPersent($id)
    {
        $investor = Investor::find()->where(['project_id' => $id])->all();
        $persent = 0;
        if (!empty($investor)) {

            foreach ($investor as $invest) {
                $persent += $invest->persent;
            }
        }
        switch ($persent) {
            case $persent < 100:
                $return = '<center><span class="label bg-yellow "> ' . $persent . '%</span></center>';;
                break;
            case $persent == 100:
                $return = '<center><span class="label bg-green ">' . $persent . '%</span></center>';
                break;
            case $persent > 100:
                $return = '<span class="label bg-red "> ' . $persent . '</span>';
                break;
        }
        return $return;

    }

}

controllers/ProjectController.php
<?php

namespace app\controllers;

use app\models\AuthAssignment;
use app\models\Photo;
use app\models\Stage;
use app\models\Status;
use app\models\UploadForm;
use app\models\File;
use Yii;
use app\models\Project;
use app\models\ProjectSearch;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ProjectController implements the CRUD actions for Project model.
 */
class ProjectController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),

                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],

                    ],

                    [
                        'actions' => ['index','create','update','image','view','file'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['image','view','file'],
                        'allow' => true,
                        'roles' => ['investor'],
                    ],

                ],

            ],

        ];
    }

    /**
     * Lists all Project models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }

    /**
     * Displays a single Project model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $files = File::find()->where(['project_id' => $id,'type'=>1])->all();
        $photos = Photo::find()->where(['project_id'=> $id,'type'=>3])->all();
        return $this->render('view', [
            'model' => $this->findModel($id),
            'photos' =>$photos,
            'files'=> $files
        ]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Project();
        $upload = new UploadForm();
        $upload->scenario = 'project';

//        $upload->scenario = 'create';
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            $upload->avatar($model->id);


            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'status' => ArrayHelper::map(Status::find()->all(), 'id', 'name'),
                'upload' => $upload,


            ]);
        }
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $upload = new UploadForm();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            if (!empty($upload->imageFile)) {

                $upload->avatar($model->id);
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'status' => ArrayHelper::map(Status::find()->all(), 'id', 'name'),
                'upload' => $upload,
            ]);
        }
    }

    /**
     * Deletes an existing Project model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
//    public function actionDelete($id)
//    {
//        $this->findModel($id)->delete();
//
//        return $this->redirect(['index']);
//    }

    /**
     * Finds the Project model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    public function actionImage($id)
    {
        $model = $this->findModel($id);
        $photoModel = new Photo();
        $upload = new UploadForm();

        $photos = Photo::find()->where(['project_id'=> $id,'type'=>3])->all();

        if ( $photoModel->load(Yii::$app->request->post()) ) {
            $upload->files = UploadedFile::getInstances($upload, 'files');
            if (!empty($upload->files)) {
                $upload->photos($photoModel->stage_id,$model->id);
            }
            return $this->redirect(['index']);
        }

        return $this->render('image', [
            'model' => $model,
            'photoModel' =>$photoModel,
            'upload' => $upload,
            'photos' =>$photos,
            'stage' => ArrayHelper::map(Stage::find()->all(), 'id', 'name'),
        ]);
    }

    public function actionFile($id)
    {
        $model = $this->findModel($id);
        $upload = new UploadForm();
        $upload->scenario = 'documents';

        $files = File::find()->where(['project_id'=>$id,'type'=>1])->all();
        if ( !empty($_POST) ) {

            $upload->files = UploadedFile::getInstances($upload, 'files');
            if (!empty($upload->files)) {

                $upload->projectDocuments($id);
            }
            return $this->redirect(['index']);
        }
        return $this->render('file', [
            'upload' => $upload,
            'files' =>$files,
            'model'=>$model
        ]);
    }
}

views/project/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-form">

    <div class="box box-default">

        <div class="box-body">

            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!--            --><?//= $form->field($model, 'kurs')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'status')->dropDownList($status) ?>


            <?= $form->field($upload, 'imageFile')->fileInput()->label(false) ?>



        </div>

        <?php if (!$model->isNewRecord): ?>
            <div class="box-body">
                <div id='gallery'>
                    <a href="<?= Yii::getAlias('@web') . '/images/project/' . $model->id . '/' . $model->avatar->path ?> "><img
                            style="width: 240px" class="news-img"
                            src="<?= Yii::getAlias('@web') . '/images/project/' . $model->id . '/cropped/' . $model->avatar->path ?>"></a>
                </div>
            </div>
        <?php endif; ?>

        <div class="box-footer">
            <div class="form-btn">
                <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/project/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProjectSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options'=>array('class'=>'form-inline')
    ]); ?>

<?= $form->field($model, 'id', [
                'template'=>'{input}<span class="input-group-btn"><button class="btn btn-warning btn-flat" type="submit"><i class="fa fa-search"></i></button></span>',
                'options'=>['class'=>'input-group input-group-sm']])
                ->textInput(['placeholder'=>Yii::t('app', 'Search')]);
            ?>

    <?php ActiveForm::end(); ?>

</div>

views/project/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Project */

$this->title = 'Create Project';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-create">

    <?= $this->render('_form', [
        'model' => $model,
        'status' => $status,
        'upload' => $upload,

    ]) ?>

</div>

views/project/file.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-form">

    <div class="box box-default">

        <div class="box-body">
            <?php if (Yii::$app->user->can('admin') || Yii::$app->user->can('moder')): ?>
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'name')->hiddenInput(['value'=>$model->name])->label(false) ?>

            <?= $form->field($upload, 'files[]')->fileInput(['multiple' => true]) ?>




            <div class="box-footer">
                <div class="form-btn">
                    <?= Html::submitButton( 'Добавить Файли', ['class' => 'btn btn-success' ]) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>

            <?php endif;?>

            <?php if (!empty($files)): ?>
                <div class="box-body">
                    <h3>Документы</h3>
                    <?php foreach ($files as $count=> $file): ?>
                        <div>
                            <img  style="width: 40px" src="<?=Yii::getAlias('@web'). '/images/file.png '?>">
                            <a class="btn btn-default" href="<?= Yii::getAlias('@web') . '/images/file/' . $file->project_id . '/' . $file->path ?>" download="<?=  $file->path ?>"> Скачать файл_<?= $count?></a>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>

    </div>

views/project/image.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-form">

    <div class="box box-default">

        <div class="box-body">
            <?php if (Yii::$app->user->can('admin') || Yii::$app->user->can('moder')): ?>
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($photoModel, 'stage_id')->dropDownList($stage) ?>


            <?= $form->field($upload, 'files[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>




            <div class="box-footer">
                <div class="form-btn">
                    <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>
            <?php endif;?>
            <?php if (!empty($photos)): ?>
                <div class="box-body">
                    <div id='gallery'>
                        <?php foreach ($photos as $photo): ?>

                            <a href="<?= Yii::getAlias('@web') . '/images/stage/' . $photo->stage_id . '/' . $photo->path ?> "><img
                                    style="width: 240px" class="news-img"
                                    src="<?= Yii::getAlias('@web') . '/images/stage/' . $photo->stage_id . '/cropped/' . $photo->path ?>"></a>

                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>

    </div>

views/project/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Projects';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-index">

    <div class="box">

        <div class="box-header with-border">
            <div class="pull-left">
                <?php if (Yii::$app->user->can('admin')): ?>
                    <?= Html::a('Создать обьект', ['create'], ['class' => 'btn btn-success']) ?>


                <?php endif; ?>
            </div>
            <div class="pull-right">
                <?php echo $this->render('_search', ['model' => $searchModel]); ?>
            </div>
        </div>

        <div class="box-body">

            <?= GridView::widget(['dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => ['name',



                    [
                        'attribute' => 'datetime',
                        'filter' => \yii\jui\DatePicker::widget(['model' => $searchModel, 'attribute' => 'datetime',
                            'language' => 'ru',
                            'dateFormat' => 'yyyy-MM-dd',
                            'options' => ['class' => 'form-control'],
                        ]),
                        'content' => function ($data) {
                            if (!empty($data->datetime)) {
                                return date('d.m.Y H:i:s', $data->datetime);
                            }
                        }
                    ],

                    [
                        'attribute' => 'status',
                        'label'=>'Статус',
                        'format' => 'raw',
                        'value' => function($data){

                            $status = $data->statuses->name;
                            switch ($status) {
                                case 'новый':
                                    return '<span class="label bg-yellow "> ' . $data->statuses->name . '</span>';
                                    break;
                                case 'подтвержденный':
                                    return '<span class="label bg-green "> ' . $data->statuses->name . '</span>';
                                    break;
                                case 'законченый':
                                    return '<span class="label bg-blue "> ' . $data->statuses->name . '</span>';
                                    break;
                                default:
                                    return $data->status->name;
                                    break;
                            }
                        }
                    ],
//                    [
//                        'attribute' =>'kurs',
//                        'label' => 'Процент',
//                        'format' => 'raw',
//                        'value' => function($data){
//                            return $data->getPersent($data->id);
//                        }
//                    ],



                    [
                        'attribute' => 'avatar_id',
                        'format' => 'html',
                        'label' => 'Фото',
                        'value' => function ($data) {
                            return '<img src=' . Yii::getAlias('@web') . '/images/project/' . $data->id . '/cropped/' . $data->avatar->path . '>';
                        }
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'headerOptions' => ['width' => '60'],
                        'template' => '{view} {update}  {image}{file}',


                        'buttons' => [
                            'link' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-usd"></span>', $url, [
                                    'title' => Yii::t('app', 'Work'),
                                ]);
                            },
                            'image' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-picture"></span>', $url, [
                                    'title' => Yii::t('app', 'Work'),
                                ]);
                            },

                            'file' => function ($url, $model) {
                                return Html::a('&nbsp; <span class="glyphicon glyphicon-folder-open"></span>', $url, [
                                    'title' => Yii::t('app', 'File'),
                                ]);
                            },

                        ],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            switch($action){
                                case 'link':
                                    $url = \yii\helpers\Url::toRoute(['investor/index','id'=>$model->id]);
                                    return $url;
                                case 'update':
                                    $url = \yii\helpers\Url::toRoute(['project/update','id'=>$model->id]);
                                    return $url;
                                case 'view':
                                    $url = \yii\helpers\Url::toRoute(['project/view','id'=>$model->id]);
                                    return $url;
                                case 'delete':
                                    $url = \yii\helpers\Url::toRoute(['project/delete','id'=>$model->id]);
                                    return $url;
                                case 'image':
                                    $url = \yii\helpers\Url::toRoute(['project/image','id'=>$model->id]);
                                    return $url;
                                case 'file':
                                    $url = \yii\helpers\Url::toRoute(['project/file','id'=>$model->id]);
                                    return $url;
                            }


                        }
                    ],
                ],
            ]); ?>
        </div>

    </div> <!--end box -->

</div>

views/project/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Project */

$this->title = 'Update Project' . ' #' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="project-update">

    <?= $this->render('_form', [
        'model' => $model,
        'status' => $status,
        'upload' => $upload,
    ]) ?>

</div>

views/project/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Project */

$this->title = 'View Project' . ' #' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-view">

    <div class="box">

        <div class="box-header with-border">


            <?php if(Yii::$app->user->can('admin')):?>
        <?= Html::a('Главная', ['index'], ['class' => 'btn btn-warning']) ?>

        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?php else:?>
            <?= Html::a('Главная', ['finance/main'], ['class' => 'btn btn-warning']) ?>
            <?php endif;?>
<!--        --><?//= Html::a('Delete', ['delete', 'id' => $model->id], [
//            'class' => 'btn btn-danger',
//            'data' => [
//                'confirm' => 'Are you sure you want to delete this item?',
//                'method' => 'post',
//            ],
//        ]) ?>

        </div>

        <div class="box-body">
        <?php $model->datetime = date('d.m.Y H:i:s', $model->datetime)?>
            <?php $status = \app\models\Status::find()->where(['id'=>$model->status])->one();
            $model->status = $status->name?>
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
//                'id',
            'name',
//            'kurs',
//                [
//                    'attribute' => 'datetime',
//
//                    'content' => function ($data) {
//                        if (!empty($data->datetime)) {
//                            return date('d.m.Y H:i:s', $data->datetime);
//                        }
//                    }
//                ],
            'datetime',
            'status',
            ],
        ]) ?>


            <?php if (!empty($photos)): ?>
                <div class="box-body">
                    <div id='gallery'>
                        <?php foreach ($photos as $photo): ?>

                            <a href="<?= Yii::getAlias('@web') . '/images/stage/' . $photo->stage_id . '/' . $photo->path ?> "><img
                                    style="width: 240px" class="news-img"
                                    src="<?= Yii::getAlias('@web') . '/images/stage/' . $photo->stage_id . '/cropped/' . $photo->path ?>"></a>

                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if (!empty($files)): ?>
                <div class="box-body">
                    <h3>Документы</h3>
                    <?php foreach ($files as $count=> $file): ?>
                        <div>
                            <img  style="width: 40px" src="<?=Yii::getAlias('@web'). '/images/file.png '?>">
                            <a class="btn btn-default" href="<?= Yii::getAlias('@web') . '/images/file/' . $file->project_id . '/' . $file->path ?>" download="<?=  $file->path ?>"> Скачать файл_<?= $count?></a>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>

    </div>

</div>