models/Work.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "work".
 *
 * @property integer $id
 * @property string $datetime
 * @property integer $operator_id
 * @property integer $status_id
 * @property integer $stage_id
 * @property integer $work_id
 * @property string $note
 * @property string $money
 * @property string $money_picture
 * @property integer $project_id
 */
class Work extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'work';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['brigade_id', 'status_id', 'stage_id', 'work_id',  'project_id', 'price', 'number'], 'required'],
            [['brigade_id', 'status_id', 'stage_id', 'work_id', 'money_picture', 'project_id'], 'integer'],
            [['note'], 'string'],
            [['money', 'price', 'number'], 'number'],
            [['datetime', 'kurs'], 'string', 'max' => 45],
        ];
    }


    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->datetime = time();
                $this->money = round($this->price*$this->number,2);

            }
            return true;
        }
        return false;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'datetime' => 'Время',
            'brigade_id' => 'Бригада',
            'status_id' => 'Статус',
            'stage_id' => 'Ступень',
            'work_id' => 'Выполеные работы',
            'note' => 'Описание',
            'money_picture' => 'Изображения',
            'project_id' => 'Проект',
            'kurs' => 'Курс',
            'is_paid' => 'Не оплаченые',
            'price'=>'Цена за единицу',
            'number'=>'Количество',
            'money' => 'Общая стоимость',
        ];
    }


    public function getBrigade()
    {
        return $this->hasOne(Brigade::className(), ['id' => 'brigade_id']);
    }

    public function getAvatar()
    {
        return $this->hasOne(Photo::className(), ['id' => 'money_picture']);
    }

    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }

    public function getStage()
    {
        return $this->hasOne(Stage::className(), ['id' => 'stage_id']);
    }

    public function getWork()
    {
        return $this->hasOne(Works::className(), ['id' => 'work_id']);
    }


//    public function getOperator()
//    {
//        return $this->hasOne(Users::className(), ['id' => 'operator_id']);
//    }

    public function getProject()
    {
        return $this->hasOne(Project::className(), ['id' => 'project_id']);
    }

    public function getSuccess()
    {
        return $this->hasMany(WorkMoney::className(), ['work_id' => 'id'])->sum('money');

    }

}

models/Works.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "works".
 *
 * @property integer $id
 * @property integer $state_id
 * @property string $name
 */
class Works extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'works';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['state_id', 'name'], 'required'],
            [['state_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
        ];
    }




    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'state_id' => 'Ступень',
            'name' => 'Название',
        ];
    }

    public function getStage()
    {
        return $this->hasOne(Stage::className(), ['id' => 'state_id']);
    }
}

controllers/WorkController.php
<?php

namespace app\controllers;

use app\models\AuthAssignment;
use app\models\Brigade;
use app\models\File;
use app\models\Investor;
use app\models\Material;
use app\models\MaterialMoney;
use app\models\Project;
use app\models\ProjectSearch;
use app\models\Stage;
use app\models\Status;
use app\models\UploadForm;
use app\models\Users;
use app\models\WorkMoney;
use app\models\Works;
use Yii;
use app\models\Work;
use app\models\WorkSearch;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * WorkController implements the CRUD actions for Work model.
 */
class WorkController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),

                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['main', 'index', 'create', 'update', 'view', 'stage', 'work', 'success'],
                        'allow' => true,
                        'roles' => ['admin', 'moder', 'operatorWork', 'operatorMaterial'],
                    ],

                    [
                        'actions' => ['view'],
                        'allow' => true,
                        'roles' => ['investor'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Work models.
     * @return mixed
     */
    public function actionIndex($id)
    {
        $model = Project::findOne($id);
        $searchModel = new WorkSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $id);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Work model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $files = File::find()->where(['work_id' => $id])->all();

        $work_id = $model->work_id;
        $project_id = $model->project_id;
        $model->datetime = date('d.m.Y H:i:s', $model->datetime);
        $model->brigade_id = $model->brigade->name;
        $model->status_id = $model->status->name;
        $model->stage_id = $model->stage->name;
        $model->work_id = $model->work->name;
        $model->project_id = $model->project->name;

        return $this->render('view', [
            'model' => $model,
            'work_id' => $work_id,
            'project_id' => $project_id,
            'files' => $files,
        ]);
    }

    /**
     * Creates a new Work model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($project_id)
    {
        $model = new Work();
        $upload = new UploadForm();
//        $money = new WorkMoney();
        $file = new UploadForm();
//        $upload->scenario = 'create';
//        $file->scenario = 'documents';
//        $project = Project::findOne($project_id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

//            $money->work_id = $model->id;
//            $money->project_id = $model->project_id;
//            $money->kurs = $model->kurs;
//            $money->save();
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            $upload->money($model->id, $project_id);

            $file->files = UploadedFile::getInstances($file, 'files');
            $file->workDocuments($model->id, $project_id);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'project_id' => $project_id,
                'status' => ArrayHelper::map(Status::find()->all(), 'id', 'name'),
                'stage' => ArrayHelper::map(Stage::find()->all(), 'id', 'name'),
                'brigade' => ArrayHelper::map(Brigade::find()->all(), 'id', 'name'),
                'upload' => $upload,
                'file' => $file,
            ]);
        }
    }

    /**
     * Updates an existing Work model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $upload = new UploadForm();
//        $money = new WorkMoney();
        $file = new UploadForm();
        if ($model->status_id == 1) {


            if ($model->load(Yii::$app->request->post())) {
                $model->money = $model->price * $model->number;
                $model->save();

//                $money->work_id = $model->id;
//                $money->project_id = $model->project_id;
//                $money->kurs = $model->kurs;
//                $money->save();
                $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
                $upload->money($model->id, $model->project_id);

                $file->files = UploadedFile::getInstances($file, 'files');
                $file->workDocuments($model->id, $model->project_id);
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'status' => ArrayHelper::map(Status::find()->all(), 'id', 'name'),
                    'stage' => ArrayHelper::map(Stage::find()->all(), 'id', 'name'),
                    'brigade' => ArrayHelper::map(Brigade::find()->all(), 'id', 'name'),
                    'upload' => $upload,
//                    'money' => $money,
                    'file' => $file,
                ]);
            }
        }
        return $this->redirect(['index', 'id' => $model->project_id]);
    }


    /**
     * Finds the Work model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Work the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Work::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    public function actionMain()
    {
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('main', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionWork()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {

            $parents = $_POST['depdrop_parents'];

            if ($parents != null) {
                $cat_id = $parents[0];

                $out = self::getWorkList($cat_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    public function getWorkList($work_id)
    { // could be a static func as well
        $data = Works::find()->where(['state_id' => $work_id])->all();
        $value = (count($data) == 0) ? ['' => ''] : $data;

        return $value;
    }

    public function actionStage()
    {

        $model = new Works();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            return $this->redirect(['index']);
        } else {
            return $this->render('stage', [
                'model' => $model,
                'stage' => ArrayHelper::map(Stage::find()->all(), 'id', 'name'),

            ]);
        }


    }


    public function actionSuccess($id)
    {
        $request = Yii::$app->request;
        $workModel = Work::findOne($id);
        $workModel->datetime = date('d.m.Y H:i:s', $workModel->datetime);
        $workModel->brigade_id = $workModel->brigade->name;
        $workModel->status_id =$workModel->status->name;
        $workModel->stage_id = $workModel->stage->name;
        $workModel->work_id = $workModel->work->name;
        $workModel->project_id = $workModel->project->name;
        $work_moneys = WorkMoney::find()->where(['work_id' => $id])->all();
        $money = 0;
        foreach ($work_moneys as $work_money) {
            $money += $work_money->money;
        }
        $investors = AuthAssignment::find()->where(['item_name' => 'investor'])->all();
        $user = [];
        foreach ($investors as $investor) {
            if ($investor->user->status == 10) {
                $sum = Investor::sumMoney($investor->user_id);
                $user [$investor->user_id] = $investor->user->name.'('.$sum.')';
            }
        }
//        print_r($workModel->money);
//        print_r($money);die();
        $model = new MaterialMoney();
//        $model->scenario = 'update';
        if ($model->load($request->post()) ) {
            $model->save();
            $workModel = Work::findOne($id);
            $workModel->status_id = 2;
            $workModel->save();
            return $this->redirect(['index', 'id' => $workModel->project_id]);
        } else {
            return $this->render('success', [
                'model' => $model,
                'id' => $id,

controllers/WorksController.php
<?php

namespace app\controllers;

use app\models\Stage;
use Yii;
use app\models\Works;
use app\models\WorksSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * WorksController implements the CRUD actions for Works model.
 */
class WorksController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Works models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new WorksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Works model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Works model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Works();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'stage' => ArrayHelper::map(Stage::find()->all(), 'id', 'name'),
            ]);
        }
    }

    /**
     * Updates an existing Works model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'stage' => ArrayHelper::map(Stage::find()->all(), 'id', 'name'),
            ]);
        }
    }

    /**
     * Deletes an existing Works model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Works model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Works the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Works::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/work/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Work */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="work-form">

    <div class="box box-default">

        <div class="box-body">

            <?php $form = ActiveForm::begin([
                'options' => [
                    'enctype' => 'multipart/form-data',
                ]
            ]); ?>

            <?= $form->field($model, 'brigade_id')->dropDownList($brigade) ?>
            <?php if(Yii::$app->user->can('admin')):?>
            <?= $form->field($model, 'status_id')->dropDownList($status) ?>
            <?php else:?>
                <?= $form->field($model, 'status_id')->hiddenInput(['value'=>1])->label(false); ?>
            <?php endif;?>
            <?= $form->field($model, 'stage_id')->dropDownList($stage, ['id'=>'cat-id','prompt' => 'Выберите ступень']) ?>

            <?php if(Yii::$app->user->can('admin')):?>
            <h4>Чтобы добавить не существующие в списке "Выполненые работы" воспользуйтесь этой кнопкой &nbsp;<?= Html::a('Добавить', ['stage' ], ['class' => 'btn btn-success','target'=>'blank']) ?></h4>
            <?php endif;?>
            <?= $form->field($model, 'work_id')->widget(\kartik\depdrop\DepDrop::classname(), [
                'options' => ['id' => 'subcat-id'],
                'pluginOptions' => [
                    'depends' => ['cat-id'],
                    'placeholder' => 'Выберите...',
                    'url' => \yii\helpers\Url::to(['/work/work'])
                ]
            ]); ?>

            <?= $form->field($model, 'note')->textarea(['rows' => 6]) ?>


            <?= $form->field($model, 'price')->textInput(['maxlength' => true,'id'=>'price']) ?>


            <?= $form->field($model, 'number')->textInput(['maxlength' => true,'id'=>'number']) ?>


            <?= $form->field($model, 'money')->textInput(['maxlength' => true,'id'=>'sum-money','disabled' => 'disabled']) ?>




            <?= $form->field($upload, 'imageFile')->fileInput()->label('Фото Стоимости') ?>

            <?= $form->field($model, 'project_id')->hiddenInput(['value' => $project_id])->label(false); ?>

            <?= $form->field($file, 'files[]')->fileInput(['multiple' => true])->label('Документы') ?>
<!--            <br>-->
<!--            --><?php //if($model->isNewRecord):?>
<!--            <h3>Деньги</h3>-->
<!---->
<!---->
<!---->
<!--            --><?//= $form->field($money, 'money')->textInput(['maxlength' => true]) ?>
<!---->
<!--            --><?//= $form->field($money, 'text')->textarea(['rows' => 6]) ?>
<!---->
<!---->
<!--            --><?php //endif; ?>

            <?php if (!$model->isNewRecord && !empty($model->money_picture)): ?>
                <div class="box-body">
                    <div id='gallery'>
                        <a href="<?= Yii::getAlias('@web') . '/images/work/' . $model->id . '/' . $model->avatar->path ?> "><img
                                style="width: 240px" class="news-img"
                                src="<?= Yii::getAlias('@web') . '/images/work/' . $model->id . '/cropped/' . $model->avatar->path ?>"></a>
                    </div>
                </div>
            <?php endif; ?>

        </div>

        <div class="box-footer">
            <div class="form-btn">
                <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/work/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\WorkSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="work-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options'=>array('class'=>'form-inline')
    ]); ?>

<?= $form->field($model, 'id', [
                'template'=>'{input}<span class="input-group-btn"><button class="btn btn-warning btn-flat" type="submit"><i class="fa fa-search"></i></button></span>',
                'options'=>['class'=>'input-group input-group-sm']])
                ->textInput(['placeholder'=>Yii::t('app', 'Search')]);
            ?>

    <?php ActiveForm::end(); ?>

</div>

views/work/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\WorkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Works';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-index">

    <div class="box">

        <div class="box-header with-border">
            <div class="pull-left">
                <?= Html::a('Создать', ['create', 'project_id' => $model->id], ['class' => 'btn btn-success']) ?>
            </div>
            <div class="pull-right">
                <?php echo $this->render('_search', ['model' => $searchModel]); ?>
            </div>
        </div>

        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [


                    [
                        'attribute' => 'brigade_id',
                        'value' => function ($data) {
                            return $data->brigade->name;
                        }
                    ],

                    [
                        'attribute' => 'stage_id',
                        'value' => function ($data) {
                            return $data->stage->name;
                        }
                    ],
                    [
                        'attribute' => 'work_id',
                        'value' => function ($data) {
                            return $data->work->name;
                        }
                    ],
                    [
                        'attribute' => 'status_id',
                        'label' => 'Статус',
                        'format' => 'raw',
                        'value' => function ($data) {

                            $status = $data->status->name;
                            switch ($status) {
                                case 'новый':
                                    return '<span class="label bg-green "> ' . $data->status->name . '</span>';
                                    break;
                                case 'подтвержденный':
                                    return '<span class="label bg-blue "> ' . $data->status->name . '</span>';
                                    break;
                                case 'законченый':
                                    return '<span class="label bg-yellow "> ' . $data->status->name . '</span>';
                                    break;
                                default:
                                    return $data->status->name;
                                    break;
                            }
                        }
                    ],
                    'money',

                    [
                        'attribute' => 'success',
                        'label' => 'Оплачено',


                    ],

                    'price',
                    'number',

                    [
                        'attribute' => 'datetime',
                        'filter' => \yii\jui\DatePicker::widget(['model' => $searchModel, 'attribute' => 'datetime',
                            'language' => 'ru',
                            'dateFormat' => 'yyyy-MM-dd',
                            'options' => ['class' => 'form-control'],
                        ]),
                        'content' => function ($data) {
                            if (!empty($data->datetime)) {
                                return date('d.m.Y H:i:s', $data->datetime);
                            }
                        }
                    ],


                    [
                        'class' => 'yii\grid\ActionColumn',
                        'headerOptions' => ['width' => '70'],
                        'template' => '{success} {view} {update}{money}{question}',
                        'visibleButtons' => [
                            'update' => function ($model, $key, $index) {
                                return $model->status_id == 1;
                            },
                            'money' => function ($model, $key, $index) {
                                return $model->success < $model->money;
                            },
                            'success' => function ($model, $key, $index) {
                                return $model->status_id == 1 && Yii::$app->user->can('admin');
                            },
                        ],

                        'buttons' => [
                            'money' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-usd"></span>', $url, [
                                    'title' => Yii::t('app', 'Work'),
                                ]);
                            },
                            'question' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-question-sign"></span>', $url, [
                                    'title' => Yii::t('app', 'Question'),
                                ]);
                            },
                            'success' => function ($url, $model) {
                                return \yii\helpers\Html::a('<span class="glyphicon glyphicon-ok"></span>&nbsp;', $url, [
                                    'role' => 'modal-remote', 'title' => 'Success', 'data-toggle' => 'tooltip'
                                ]);
                            },


                        ],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            switch ($action) {
                                case 'money':
                                    $url = \yii\helpers\Url::toRoute(['work-money/index', 'id' => $model->id]);
                                    return $url;
                                case 'update':
                                    $url = \yii\helpers\Url::toRoute(['work/update', 'id' => $model->id]);
                                    return $url;
                                case 'view':
                                    $url = \yii\helpers\Url::toRoute(['work/view', 'id' => $model->id]);
                                    return $url;
                                case 'question':
                                    $url = \yii\helpers\Url::toRoute(['work-comment/index', 'id' => $model->id]);
                                    return $url;
                                case 'success':
                                    $url = \yii\helpers\Url::to(['work/success', 'id' => $model->id,]);
                                    return $url;

                            }


                        }

                    ],
                ],
            ]); ?>
        </div>

    </div> <!--end box -->

</div>
<?php \yii\bootstrap\Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php \yii\bootstrap\Modal::end(); ?>

views/work/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Work */

$this->title = 'View Work' . ' #' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Works', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-view">

    <div class="box">

        <div class="box-header with-border">
            <?= Html::a('Назад', ['index', 'id' => $project_id], ['class' => 'btn btn-warning']) ?>
            <?= Html::a('Создать', ['create', 'project_id' => $project_id], ['class' => 'btn btn-success']) ?>
            <?php if (!$model->status_id == 2): ?>
                <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?php endif ?>
            <!--        --><? //= Html::a('Delete', ['delete', 'id' => $model->id], [
            //            'class' => 'btn btn-danger',
            //            'data' => [
            //                'confirm' => 'Are you sure you want to delete this item?',
            //                'method' => 'post',
            //            ],
            //        ]) ?>

        </div>

        <div class="box-body">

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
//                'id',
                    'datetime',
                    'brigade_id',
                    'status_id',
                    'stage_id',
                    'work_id',
                    'note:ntext',
                    'money',
                    'price',
                    'number',
                    'project_id',
                ],
            ]) ?>

            <?php if (!empty($model->money_picture)): ?>
                <div class="box-body">
                    <div id='gallery'>


                        <a href="<?= Yii::getAlias('@web') . '/images/work/' . $model->id . '/' . $model->avatar->path ?> "><img
                                style="width: 240px" class="news-img"
                                src="<?= Yii::getAlias('@web') . '/images/work/' . $model->id . '/cropped/' . $model->avatar->path ?>"></a>


                    </div>
                </div>
            <?php endif; ?>
            <?php if (!empty($files)): ?>
            <div class="box-body">
                <h3>Документы</h3>
                <?php foreach ($files as $count=> $file): ?>
                    <div>
                        <img  style="width: 40px" src="<?=Yii::getAlias('@web'). '/images/file.png '?>">
                    <a class="btn btn-default" href="<?= Yii::getAlias('@web') . '/images/file/' . $file->work_id . '/' . $file->path ?>" download="<?=  $file->path ?>"> Скачать файл_<?= $count?></a>
                    </div>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>

        </div>

    </div>

</div>