models/FabricTest.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "fabric".
 *
 * @property integer $id
 * @property integer $material_id
 * @property double $money
 * @property integer $money_picture
 * @property string $kurs
 * @property integer $project_id
 * @property integer $is_paid
 * @property double $price
 * @property double $number
 * @property integer $nomenclatura_id
 */
class FabricTest extends \yii\db\ActiveRecord
{

    public $project;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'fabric';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['material_id', 'money', 'kurs', 'project_id', 'price', 'number', 'nomenclatura_id'], 'required','on'=>'create'],

            [[ 'project_id',  'nomenclatura_id'], 'required','on'=>'create_nomenklatura'],

            [['material_id', 'money_picture', 'project_id', 'is_paid', 'nomenclatura_id'], 'integer'],
            [['money', 'price', 'number'], 'number'],
            [['kurs'], 'string', 'max' => 255],
            [['type'], 'string', 'max' => 50],
            [['nomenclatura_id'], 'exist', 'skipOnError' => true, 'targetClass' => Nomenclatura::className(), 'targetAttribute' => ['nomenclatura_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'datetime' => 'Дата',
            'brigade' => 'Поставщик',
            'status_id' => 'Статус',
            'material_id' => 'Материал',
            'money_picture' => 'Фото',
            'kurs' => 'Курс',
            'project_id' => 'Проект',
            'price'=>'Цена за единицу',
            'number'=>'Количество',
            'money' => 'Общая стоимость',
        ];

    }

    public function getNomenclatura()
    {
        return $this->hasOne(Nomenclatura::className(), ['id' => 'nomenclatura_id']);
    }


    public function getMaterial()
    {
        return $this->hasOne(Material::className(), ['id' => 'material_id']);
    }


    public function getProject()
    {
        return $this->hasOne(Project::className(), ['id' => 'project_id']);
    }
}

controllers/FabricTestController.php
<?php

namespace app\controllers;

use app\models\AuthAssignment;
use app\models\Fabric;
use app\models\Investor;
use app\models\Material;
use app\models\MaterialMoney;
use app\models\Nomenclatura;
use app\models\UploadForm;
use Yii;
use app\models\FabricTest;
use app\models\FabricTestSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * FabricTestController implements the CRUD actions for FabricTest model.
 */
class FabricTestController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                    'bulk-create' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all FabricTest models.
     * @return mixed
     */
    public function actionIndex($id)
    {    
        $searchModel = new FabricTestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$id);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'project_id'=>$id,
        ]);
    }


    /**
     * Displays a single FabricTest model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Материал #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new FabricTest model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $request = Yii::$app->request;
        $nomenklaturaModel = Nomenclatura::findOne($id);
        $model = new FabricTest();



//        $model->scenario = 'create';
        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить новый материал",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                        'id'=>$id,
                        'project_id'=>$nomenklaturaModel->project_id,
                        'material' => ArrayHelper::map(Material::find()->addOrderBy('name')->all(), 'id', 'name'),

                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) ){
                $model->money = $model->price* $model->number;
                $model->save();

                $is_null = FabricTest::find()->where(['nomenclatura_id'=>$model->nomenclatura_id,'type'=>'create'])->one();
                if(!empty($is_null))
                {
                    $is_null->delete();
                }
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Добавить новый материал",
                    'content'=>'<span class="text-success">Создано Успешно</span>',
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Добавить еще',['create','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Добавить новый материал",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                        'id'=>$id,
                        'project_id'=>$nomenklaturaModel->project_id,
                        'material' => ArrayHelper::map(Material::find()->all(), 'id', 'name'),

                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Добавить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'id'=>$id,
                    'project_id'=>$nomenklaturaModel->project_id,
                    'material' => ArrayHelper::map(Material::find()->all(), 'id', 'name'),
                ]);
            }
        }
       
    }

    /**
     * Updates an existing FabricTest model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
//        $nomenklaturaModel = Nomenclatura::findOne($id);

//        $model->scenario = 'create';
        if($request->isAjax){

            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить материал #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                        'material' => ArrayHelper::map(Material::find()->all(), 'id', 'name'),
                        'project_id'=>$model->project_id,
                        'id'=>$model->nomenclatura_id,

                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post())){
                $model->money = $model->price* $model->number;
                $model->save();
//                print_r($model->getErrors());
//                die();


                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Материал #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
            }else{
                 return [
                    'title'=> "Изменить материал #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                        'material' => ArrayHelper::map(Material::find()->all(), 'id', 'name'),
                        'project_id'=>$model->project_id,
                        'id'=>$model->nomenclatura_id,

                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Добавить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'project_id'=>$model->project_id,
                    'material' => ArrayHelper::map(Material::find()->all(), 'id', 'name'),
                    'id'=>$id,
                ]);
            }
        }
    }

    /**
     * Delete an existing FabricTest model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

     /**
     * Delete multiple existing FabricTest model.
     * For ajax request will return json object

views/fabric-test/_columns.php
<?php
use yii\helpers\Url;
use \kartik\grid\GridView;

return [
//    [
//        'class' => 'kartik\grid\CheckboxColumn',
//        'width' => '20px',
//    ],
//    [
//        'class' => 'kartik\grid\SerialColumn',
//        'width' => '30px',
//    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'nomenclatura.name',
        'label' => 'Номенклатура',
        'group' => true,
        'groupedRow' => true,
//        'subGroupOf'=> 0,
        'groupOddCssClass' => 'kv-grouped-row',  // configure odd group cell css class
        'groupEvenCssClass' => 'kv-grouped-row',


    ],


    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'nomenclatura.avatar_id',
        'label' => 'Фото подтверждение',
        'group' => true,
        'format' => 'html',
        'value' => function ($data) {
            if (!empty($data->nomenclatura->avatar_id)) {
                return '<a  class="show" data-url='. Yii::getAlias('@web') . '/images/nomenclatura/' . $data->nomenclatura_id . '/' . $data->nomenclatura->avatar->path.' ><img style="width: 240px" src=' . Yii::getAlias('@web') . '/images/nomenclatura/' . $data->nomenclatura_id . '/cropped/' . $data->nomenclatura->avatar->path . '></a>';
            } else return false;
        },
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
        'groupFooter' => function ($model, $key, $index, $widget) { // Closure method
            return [
                'mergeColumns' => [[2, 3]], // columns to merge in summary
                'content' => [              // content to show in each summary cell
                    6 => 'Сумма: ',
                    10 => GridView::F_SUM,
//                    7 => GridView::F_SUM,
//                    8 => GridView::F_SUM,
                    14 => GridView::F_SUM,
                ],
                'contentFormats'=>[      // content reformatting for each summary cell
                    10=>['format'=>'number', 'decimals'=>2],
                    14=>['format'=>'number', 'decimals'=>2],
                ],
                'contentOptions'=>[      // content html attributes for each summary cell
                    10=>['style'=>'text-align:right'],
                    14=>['style'=>'text-align:right'],
                ],


                // html attributes for group summary row
                'options' => ['class' => 'success', 'style' => 'font-weight:bold;']
            ];
        },
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'nomenclatura.provider',
        'label' => 'Поставщик',
        'group' => true,
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'nomenclatura.stage.name',
        'label' => 'Этап',
        'group' => true,
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
        'content'=> function($data){
            if($data->nomenclatura->stage_id == 3)
            {
                return 'Ступень № 3,4  - Коробка';
            }
            else {
                return $data->nomenclatura->stage->name;
            }
        }
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'nomenclatura.datetime',
        'label' => 'Дата',
        'group' => true,
        'format' => 'date',
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
    ],


    [
        'class' => '\kartik\grid\DataColumn',
        'label' => 'Статус',
        'attribute' => 'nomenclatura.status.name',
        'group' => true,
        'subGroupOf' => 0,
    ],
    [
        'class' => '\kartik\grid\DataColumn',

        'attribute' => '1',
        'group' => true,
        'format' => 'html',
        'content' => function ($data) {
            $url = \yii\helpers\Url::toRoute(['fabric-test/create', 'id' => $data->nomenclatura->id]);

            return \yii\helpers\Html::a('<span class="glyphicon glyphicon-plus"></span>&nbsp;', $url, [
                'role' => 'modal-remote', 'title' => 'Update', 'data-toggle' => 'tooltip'
            ]);
        },
//        material-money/index','id'=>$model->id
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => '2',
        'group' => true,
        'format' => 'html',
        'content' => function ($data) {
            if(round($data->nomenclatura->sum,2) < round($data->nomenclatura->material,2)) {
                $url = \yii\helpers\Url::toRoute(['material-money/index', 'id' => $data->nomenclatura->id]);
                return \yii\helpers\Html::a('<span class="glyphicon glyphicon-usd"></span>&nbsp;', $url, [
                    'title' => 'Update'
                ]);
            }else{
                return false;
            }
        },
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => '3',
        'group' => true,
        'format' => 'html',
        'content' => function ($data) {
            if(Yii::$app->user->can('admin') && $data->nomenclatura->status_id==1) {
                $url = \yii\helpers\Url::toRoute(['fabric-test/success', 'id' => $data->nomenclatura->id]);
                return \yii\helpers\Html::a('<span class="glyphicon glyphicon-ok"></span>&nbsp;', $url, [
                    'title' => 'Success'
                ]);
            }else{
                return false;
            }
        },
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => '4',
        'group' => true,
        'format' => 'html',
        'content' => function ($data) {
//            if(Yii::$app->user->can('admin') && $data->nomenclatura->status_id==1) {
                $url = \yii\helpers\Url::toRoute(['nomenclatura/update', 'id' => $data->nomenclatura->id]);
                return \yii\helpers\Html::a('<span class="glyphicon glyphicon-pencil"></span>&nbsp;', $url, [
                    'title' => 'Success'
                ]);
//            }else{
//                return false;
//            }
        },
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
    ],


    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'nomenclatura.sum',
        'label' => 'Оплаченая Сумма',
        'group' => true,
        'contentOptions'=>[
            'style'=>'text-align:right'
        ],
        'content'=>function($data){
          return round($data->nomenclatura->sum,2);
        },
//        'format' => 'datetime',
//        'groupedRow'=>  true,
        'subGroupOf' => 0,
//                'format' => ['decimal', 2],
        'pageSummary' => true,
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'material.name',
        'label' => 'Материал',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'label' => 'Цена за единицу',
        'attribute' => 'price',
        'contentOptions'=>[
            'style'=>'text-align:right'
        ],

    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'label' => 'Количество',
        'attribute' => 'number',
        'contentOptions'=>[
            'style'=>'text-align:right'
        ],
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'label' => 'Стоимость',
        'attribute' => 'money',
        'contentOptions'=>[
            'style'=>'text-align:right'
        ],
//        'format' => ['decimal', 2],
        'pageSummary' => true,
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'money_picture',
//        'label'=>'Фото потверждение',
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'kurs',
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'project_id',
//    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'is_paid',
    // ],

    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'nomenclatura_id',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign' => 'middle',
        'template' => '{view} {update} {delete}',
        'visibleButtons' => [
            'update' => function ($model, $key, $index) {
                return $model->nomenclatura->status_id == 1;
            },
            'delete' => function ($model, $key, $index) {
                return $model->nomenclatura->status_id == 1;
            },
        ],
//        'buttons' => [
//            'create' => function ($url, $model) {
//                return \yii\helpers\Html::a('<span class="glyphicon glyphicon-plus"></span>&nbsp;', $url, [
//                    'role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'
//                ]);
//            },
//
//
//        ],
//        'urlCreator' => function ($action, $model, $key, $index) {
//            switch($action){
//                case 'create':
//                    $url = \yii\helpers\Url::toRoute(['fabric/create','id'=>$model->id]);
//                    return $url;
//                case 'update':
//                    $url = \yii\helpers\Url::toRoute(['fabric-test/update','id'=>$model->id]);
//                    return $url;
//                case 'view':
//                    $url = \yii\helpers\Url::toRoute(['fabric-test/view','id'=>$model->id]);
//                    return $url;
//                case 'delete':
//                    $url = \yii\helpers\Url::toRoute(['fabric-test/delete','id'=>$model->id]);
//                    return $url;
//
//
//            }
//
//
//        },

        'urlCreator' => function ($action, $model, $key, $index) {
            return Url::to([$action, 'id' => $key]);
        },
//        'createOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'viewOptions' => ['role' => 'modal-remote', 'title' => 'View', 'data-toggle' => 'tooltip'],
        'updateOptions' => ['role' => 'modal-remote', 'title' => 'Update', 'data-toggle' => 'tooltip'],
//        'deleteOptions' => ['role' => 'modal-remote', 'title' => 'Delete',
//            'data-confirm' => false, 'data-method' => false,// for overide yii data api
//            'data-request-method' => 'post',
//            'data-toggle' => 'tooltip',
//            'data-confirm-title' => 'Are you sure?',
//            'data-confirm-message' => 'Are you sure want to delete this item'],
    ],

];   

views/fabric-test/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FabricTest */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="fabric-test-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'material_id')->dropDownList($material, ['prompt' => 'Виберите материал']) ?>


<!--    --><?//= $form->field($model, 'money_picture')->textInput() ?>

    <?= $form->field($model, 'project_id')->hiddenInput(['value'=>$project_id])->label(false); ?>

<!--    --><?//= $form->field($model, 'is_paid')->textInput() ?>
    <?= $form->field($model, 'price')->textInput(['maxlength' => true,'id'=>'price']) ?>

    <?= $form->field($model, 'number')->textInput(['maxlength' => true,'id'=>'number']) ?>


    <?= $form->field($model, 'money')->textInput(['maxlength' => true, 'id' => 'sum-money','disabled' => 'disabled']) ?>


    <?= $form->field($model, 'nomenclatura_id')->hiddenInput(['value'=>$id])->label(false); ?>
<!--    --><?//= $form->field($model, 'nomenclatura_id')->textInput()->label(false); ?>





	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>
<script>
    (function ($) {

        $('#price').on('keyup', function () {
            var price = $('#price').val();
            var number = $('#number').val();
            var sum = price*number;
            $('#sum-money').val(sum.toFixed(2));
            //console.log(1);
        });


        $('#number').on('keyup', function () {
            var price = $('#price').val();
            var number = $('#number').val();
            var sum = price*number;
            $('#sum-money').val(sum.toFixed(2));
            //console.log(1);
        });

    })(jQuery);
</script>

views/fabric-test/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\FabricTest */

?>
<div class="fabric-test-create">

    <?= $this->render('_form', [
        'model' => $model,
        'id'=>$id,
        'project_id'=>$project_id,
        'material' => $material,

    ]) ?>
</div>

views/fabric-test/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\FabricTestSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Fabric Tests';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="fabric-test-index">
    <div id="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'toolbar'=> [
                ['content'=>
                    Html::a('Добавить Накладную', ['nomenclatura/create','project_id'=>$project_id],
                    ['role'=>'modal-remote','title'=> 'Create new Fabric Tests','class'=>'btn btn-default']).
                    Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                    ['data-pjax'=>1, 'class'=>'btn btn-default', 'title'=>'Reset Grid']).
                    '{toggleData}'.
                    '{export}'
                ],
            ],          
            'striped' => true,
            'condensed' => true,
            'responsive' => true,          
            'panel' => [
                'type' => 'primary', 
                'heading' => '<i class="glyphicon glyphicon-list"></i> Fabric Tests listing',
//                'before'=>'<em>* Resize table columns just like a spreadsheet by dragging the column edges.</em>',
//                'after'=>BulkButtonWidget::widget([
//                            'buttons'=>Html::a('<i class="glyphicon glyphicon-add"></i>&nbsp; Добавить Материал',
//                                ['create'] ,
//                                [
//                                    "class"=>"btn btn-success btn-xs",
//                                    'role'=>'modal-remote', 'data-toggle'=>'tooltip',
//                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
//                                    'data-request-method'=>'post',
////                                    'data-confirm-title'=>'Вы уверенны?',
////                                    'data-confirm-message'=>'Вы хотите к этой номенклатуре добавить материалы?'
//                                ]),
//                        ]).
                        '<div class="clearfix"></div>',
            ]
        ])?>
    </div>
</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/fabric-test/success.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\FabricTest */
?>
<div class="work-index">

    <div class="box">
        <div class="box-body">
            <div class="fabric-test-view">

                <?= DetailView::widget([
                    'model' => $materialModel,
                    'attributes' => [
//                'id',
                        'name',
                        'datetime',
                        'status_id',
//                        'stage_id',
//                        'money',
                        'project_id',
                    ],
                ]) ?>



                <?php $form = \yii\widgets\ActiveForm::begin(); ?>
                <?php if($money == $materialModel->material  ):?>
                    <?= $form->field($model, 'kurs')->hiddenInput(['value'=>1])->label(false); ?>
                <?php else:?>
                    <?= $form->field($model, 'money')->textInput(['maxlength' => true]) ?>
                    <?= $form->field($model, 'project_id')->hiddenInput(['value'=>$project_id])->label(false); ?>
                    <?= $form->field($model, 'investor_id')->dropDownList($user,['prompt' => 'Виберите инвестора']) ?>
                    <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>
                <?php endif;?>

                <div class="form-group">
                    <?= \yii\helpers\Html::submitButton($model->isNewRecord ? ' Подтвердить' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                </div>


                <?php \yii\widgets\ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

views/fabric-test/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\FabricTest */
?>
<div class="fabric-test-update">

    <?= $this->render('_form', [
        'model' => $model,
        'material'=>$material,
        'project_id'=>$project_id,
        'id'=>$id,
    ]) ?>

</div>

views/fabric-test/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\FabricTest */
?>
<div class="fabric-test-view">
 
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
//            'id',
            [
                'attribute'=>'nomenclatura.project.name',
                'label'=>'Проект',
            ],
            [
                'attribute'=>'nomenclatura.name',
                'label'=>'Накладная'
            ],
            'material.name',

            'money_picture',
//            'kurs',


//            'is_paid',
            'price',
            'number',
            'money',

        ],
    ]) ?>

</div>