models/Brigade.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "brigade".
 *
 * @property integer $id
 * @property string $name
 * @property string $create_datetime
 * @property string $finish_datetime
 * @property integer $status_id
 */
class Brigade extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'brigade';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status_id'], 'integer'],
            [['name', 'create_datetime', 'finish_datetime'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'create_datetime' => 'Дата создания',
            'finish_datetime' => 'Дата окончания',
            'status_id' => 'Статус',
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->create_datetime = time();
                $this->status_id = 2;
            }
            return true;
        }
        return false;
    }


    /**
     * @param bool $insert
     * @param array $changedAttributes
     * @throws \yii\db\Exception
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        if($this->status_id == 3){

            Yii::$app->db->createCommand("UPDATE `team` SET `status_id`='3' ,`finish_datetime`=".time()." WHERE `brigade_id`='$this->id' ")->execute();

        }
    }
}

controllers/BrigadeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Brigade;
use app\models\BrigadeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BrigadeController implements the CRUD actions for Brigade model.
 */
class BrigadeController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Brigade models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BrigadeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Brigade model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Brigade model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Brigade();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Brigade model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Brigade model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        $model->finish_datetime = time();
        $model->status_id = 3;
        $model->save(false);

        return $this->redirect(['index']);
    }

    /**
     * Finds the Brigade model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Brigade the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Brigade::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/brigade/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Brigade */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="brigade-form">

	<div class="box box-default">

		<div class="box-body">

	    <?php $form = ActiveForm::begin(); ?>

	    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!--    --><?//= $form->field($model, 'create_datetime')->textInput(['maxlength' => true]) ?>

<!--    --><?//= $form->field($model, 'finish_datetime')->textInput(['maxlength' => true]) ?>

<!--    --><?//= $form->field($model, 'status_id')->textInput() ?>

		</div>

	    <div class="box-footer">
			<div class="form-btn">
	        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    	</div>
	    </div>

    <?php ActiveForm::end(); ?>

    </div>

</div>

views/brigade/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BrigadeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="brigade-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options'=>array('class'=>'form-inline')
    ]); ?>

<?= $form->field($model, 'id', [
                'template'=>'{input}<span class="input-group-btn"><button class="btn btn-warning btn-flat" type="submit"><i class="fa fa-search"></i></button></span>',
                'options'=>['class'=>'input-group input-group-sm']])
                ->textInput(['placeholder'=>Yii::t('app', 'Search')]);
            ?>

    <?php ActiveForm::end(); ?>

</div>

views/brigade/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Brigade */

$this->title = 'Create Brigade';
$this->params['breadcrumbs'][] = ['label' => 'Brigades', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="brigade-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/brigade/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BrigadeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Brigades';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="brigade-index">

    <div class="box">

        <div class="box-header with-border">
            <div class="pull-left">
                <?= Html::a('Добавить бригаду', ['create'], ['class' => 'btn btn-success']) ?>
            </div>
            <div class="pull-right">
                <?php echo $this->render('_search', ['model' => $searchModel]); ?>
                    </div>
        </div>

        <div class="box-body">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            'name',
            [     'attribute' => 'create_datetime',
                'filter' => \yii\jui\DatePicker::widget(['model' => $searchModel, 'attribute' => 'create_datetime',
                    'language' => 'ru',
                    'dateFormat' => 'yyyy-MM-dd',
                    'options' => ['class' => 'form-control'],
                ]),
                'content' => function ($data) {
                    if (!empty($data->create_datetime)) {
                        return date('d.m.Y H:i:s', $data->create_datetime);
                    }
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'headerOptions' => ['width' => '70'],
                'template' => '{view} {update}{delete}{users}',


                'buttons' => [
                    'users' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-user"></span>', $url, [
                            'title' => Yii::t('app', 'Work'),
                        ]);
                    },


                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    switch($action){
                        case 'users':
                            $url = \yii\helpers\Url::toRoute(['team/index','id'=>$model->id]);
                            return $url;
                        case 'update':
                            $url = \yii\helpers\Url::toRoute(['brigade/update','id'=>$model->id]);
                            return $url;
                        case 'view':
                            $url = \yii\helpers\Url::toRoute(['brigade/view','id'=>$model->id]);
                            return $url;
                        case 'delete':
                            $url = \yii\helpers\Url::toRoute(['brigade/delete','id'=>$model->id]);
                            return $url;

                    }


                }
            ],
        ],
    ]); ?>
        </div>

    </div> <!--end box -->

</div>

views/brigade/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Brigade */

$this->title = 'Update Brigade' . ' #' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Brigades', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="brigade-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/brigade/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Brigade */

$this->title = 'View Brigade' . ' #' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Brigades', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="brigade-view">

    <div class="box">

        <div class="box-header with-border">
        <?= Html::a('Manage', ['index'], ['class' => 'btn btn-warning']) ?>
        <?= Html::a('Create', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>

        </div>

        <div class="box-body">

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
            'name',
            'create_datetime',
            'finish_datetime',
            'status_id',
            ],
        ]) ?>

        </div>

    </div>

</div>